# Generated by Django 3.2.12 on 2022-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
