# Generated by Django 3.2.12 on 2022-05-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_transaction_and_alter_type_of_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_request_to_me",
                        to="app.telegramuser",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_request_from_me",
                        to="app.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Friend Request",
                "verbose_name_plural": "Friend Requests",
                "db_table": "friend_requests",
                "unique_together": {("source", "destination")},
            },
        ),
    ]
