# Generated by Django 3.2.12 on 2022-04-30 14:02
import django.db.models.deletion
from django.apps import apps
from django.db import migrations, models

Transaction = apps.get_model("app", "Transaction")


def drop_transactions(*args):
    Transaction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20220411_2137"),
    ]

    operations = [
        migrations.RunPython(drop_transactions),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("created_at",), "verbose_name": "Transaction", "verbose_name_plural": "Transactions"},
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="bank_accounts", to="app.telegramuser"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transactions_to_me", to="app.bankaccount"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transactions_from_me", to="app.bankaccount"
            ),
        ),
    ]
