# Generated by Django 3.2.12 on 2022-05-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_friend_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="friends",
            field=models.ManyToManyField(related_name="_app_telegramuser_friends_+", to="app.TelegramUser"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("value", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="app.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "refresh_tokens",
            },
        ),
    ]
