# Generated by Django 3.2.12 on 2022-05-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_refresh_token_alter_telegram_user_alter_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=255)),
                ("tip", models.CharField(max_length=255)),
                (
                    "telegram_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="secret_key", to="app.telegramuser"
                    ),
                ),
            ],
            options={
                "verbose_name": "Secret Key",
                "verbose_name_plural": "Secret Keys",
                "db_table": "secret_keys",
            },
        ),
    ]
