image: docker/compose:alpine-1.28.0

stages:
  - build
  - lint
  - test
  - deploy

before_script:
  - apk add make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cat $DOT_ENV > $(pwd)/src/config/.env

build:
  stage: build
  script:
    - make build push
  tags:
    - job:build
  only:
    - master

lint:
  stage: lint
  tags:
    - job:lint
  script:
    - make pull lint_build
  only:
    - master

test:
  stage: test
  tags:
    - job:test
  script: make pull test_build
  only:
    - master

deploy:
  stage: deploy
  tags:
    - job:deploy
  script: make pull up
  only:
    - master
