version: "3.9"

services:
  app:
    build: .
    container_name: app
    env_file:
      - src/config/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - src/config/.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: