version: "3.9"

services:
  api:
    build: .
    image: "${IMAGE_NAME}"
    container_name: api
    command: make run_api
    restart: always
    env_file:
      - src/config/.env
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build: .
    image: "${IMAGE_NAME}"
    container_name: bot
    command: make run_bot
    restart: always
    env_file:
      - src/config/.env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    env_file:
      - src/config/.env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: