version: "3.9"

services:
  nginx:
    build: nginx/
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    build: .
    image: "${IMAGE_NAME}"
    container_name: app
    command: make static migrate run
    restart: always
    env_file:
      - src/config/.env
    volumes:
      - static:/app/static
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    env_file:
      - src/config/.env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  static: