version: "3.9"

services:
  nginx:
    build: nginx/
    container_name: nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    build: .
    container_name: app
    command: make collectstatic migrate run
    restart: always
    env_file:
      - src/config/.env
    volumes:
      - static:/app/static
      - /var/log/bank:/app/src/logs
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    env_file:
      - src/config/.env
    volumes:
      - data:/var/lib/postgresql/data

  metrics:
    build: metrics/
    container_name: metrics
    restart: always
    ports:
      - "16241:16241"
    environment:
      FOLDER_ID: "${FOLDER_ID}"
      PROC_DIRECTORY: "/ua_proc"
    volumes:
      - /proc:/ua_proc

volumes:
  data:
  static: