from .IFriendRepository import IFriendRepository
from .IFriendRequestRepository import IFriendRequestRepository
from .ISecretKeyRepository import ISecretKeyRepository
from .ITelegramUserRepository import ITelegramUserRepository
